### ISSUE TITLE
Please update our playground's api

### ISSUE THREAD

**Issue by cloudclouderson** [googleads/dfp-playground#4]
Hello googleads/dfp-playground friends, 

I just wanted to kindly request you update the playground's api. Please accept this complimentary image: https://i.pinimg.com/originals/1d/7b/27/1d7b27d0a94b643c1cb7684ed329dc06.jpg. 

ApiVersionError.UPDATE_TO_NEWER_VERSION @ version; trigger:'Version v201708 was deprecated and is now disabled. Please check the DoubleClick for Publishers blog for more information or contact us via the support forum.'

Thank you!
Cloud C.

**Comment by donovanfm** [comment]
This is now fixed. I apologize for the delay – there was an internal dependency issue that also needed to be resolved with this update.
